# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: infra

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          pip install awscli

      - name: Build
        working-directory: projects/website
        run: |
          npm ci
          npm run build --if-present

      - name: s3 sync
        run: |
          BUCKET=$(aws ssm get-parameter --name /website/bucket | jq --raw-output ".Parameter[\"Value\"]")
          aws s3 sync projects/website/dist s3://$BUCKET --delete

      - name: CloudFront invalidation
        run: |
          DIST_ID=$(aws ssm get-parameter --name /website/cloudfront/id | jq --raw-output ".Parameter[\"Value\"]")
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
