name: Full test of project
on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Setup
        working-directory: projects/website
        run: npm ci

      - name: Linting
        working-directory: projects/website
        run: npm run lint

      - name: Build
        working-directory: projects/website
        run: npm run build

      - name: Test
        working-directory: projects/website
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: infra
